import io
import re
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


def generate_simple_pdf(title: str, content: str) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    title_style.alignment = 1 # Center
    normal_style = styles['Normal']
    
    elements = []
    
    # Header Logo / App Name
    try:
        logo = Image("assets/images/logo.png", width=60, height=60)
        elements.append(logo)
    except Exception:
        pass
        
    elements.append(Paragraph("<b>Healix AI Health Assistant</b>", title_style))
    elements.append(Paragraph(title, styles['Heading3']))
    elements.append(Spacer(1, 12))
    
    # Content
    for line in content.split('\n'):
        # Convert markdown bold to reportlab bold
        line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
        if line.strip():
            elements.append(Paragraph(line, normal_style))
            elements.append(Spacer(1, 6))
            
    # Disclaimer
    elements.append(Spacer(1, 30))
    disclaimer_text = "DISCLAIMER: This report is generated by an AI Health Assistant and is strictly for informational purposes. It is NOT a medical diagnosis, and the AI is not a licensed medical professional."
    elements.append(Paragraph(disclaimer_text, ParagraphStyle('Disclaimer', parent=styles['Italic'], fontSize=9, textColor=colors.gray)))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer
